// Command collaboration-contract generates the public v2 contract and TS types.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"everything-go/internal/core"
)

func main() {
	root := flag.String("root", "..", "workspace root")
	check := flag.Bool("check", false, "check generated files without writing")
	flag.Parse()
	schema := core.CollaborationSchemas()
	encoded, err := json.MarshalIndent(schema, "", "  ")
	must(err)
	encoded = append(encoded, '\n')
	defs := schema["$defs"].(map[string]any)
	var ts strings.Builder
	ts.WriteString("// Code generated by go/cmd/collaboration-contract; DO NOT EDIT.\n")
	ts.WriteString("export type GeneratedCollaborationCommand = " + tsType(defs["command"].(map[string]any)) + "\n")
	ts.WriteString("export type GeneratedCollaborationSnapshot = " + tsType(defs["snapshot"].(map[string]any)) + "\n")
	enumAt := func(def, key string) any {
		return defs[def].(map[string]any)["properties"].(map[string]any)[key].(map[string]any)["enum"]
	}
	enums, err := json.Marshal(map[string]any{"sourceKinds": enumAt("source", "kind"), "reportKinds": enumAt("report", "kind"), "readiness": enumAt("report", "readiness"), "coverageClaims": enumAt("coverage", "claim")})
	must(err)
	ts.WriteString("export const collaborationEnums = " + string(enums) + " as const\n")
	outputs := map[string][]byte{"contracts/v3/human_ai_collaboration.schema.json": encoded, "app/src/generated/humanAICollaborationContract.ts": []byte(ts.String())}
	for relative, body := range outputs {
		path := filepath.Join(*root, relative)
		if *check {
			old, err := os.ReadFile(path)
			must(err)
			if !bytes.Equal(old, body) {
				must(fmt.Errorf("generated contract drift: %s", relative))
			}
		} else {
			must(os.MkdirAll(filepath.Dir(path), 0755))
			must(os.WriteFile(path, body, 0644))
		}
	}
}
func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func tsType(s map[string]any) string {
	if value, ok := s["const"]; ok {
		b, _ := json.Marshal(value)
		return string(b)
	}
	if values, ok := s["enum"].([]string); ok {
		parts := []string{}
		for _, v := range values {
			b, _ := json.Marshal(v)
			parts = append(parts, string(b))
		}
		return strings.Join(parts, " | ")
	}
	switch s["type"] {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		return "Array<" + tsType(s["items"].(map[string]any)) + ">"
	case "object":
		if props, ok := s["properties"].(map[string]any); ok {
			keys := []string{}
			for k := range props {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			required := map[string]bool{}
			if rows, ok := s["required"].([]string); ok {
				for _, k := range rows {
					required[k] = true
				}
			}
			parts := []string{}
			for _, k := range keys {
				optional := "?"
				if required[k] {
					optional = ""
				}
				parts = append(parts, k+optional+": "+tsType(props[k].(map[string]any)))
			}
			return "{ " + strings.Join(parts, "; ") + " }"
		}
		if child, ok := s["additionalProperties"].(map[string]any); ok {
			return "Record<string, " + tsType(child) + ">"
		}
		return "Record<string, unknown>"
	default:
		return "unknown"
	}
}
